spring:
  datasource:
    url: jdbc:mysql://10.254.1.47:3306/caishen_game_three?zeroDateTimeBehavior=CONVERT_TO_NULL
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  profiles:
    active: dev
  redis:
    host: 10.254.1.36
    port: 6379
    database: 1
    jedis:
      pool:
        max-active: 200 # 连接池最大连接数
        max-wait: -1  # 连接池最大阻塞等待时间
        max-idle: 10 # 连接池中的最大空闲连接
        min-idle: 0 # 连接池中的最小空闲连接
    timeout: 5000
  rabbitmq:
    host: 10.254.1.36
    port: 5672
    username: caishen
    password: 123456
    publisher-returns: true
    listener:
      simple:
        concurrency: 10    #消费者数量
        max-concurrency: 10     #最大消费者数量
        prefetch: 1     #消费者每次从队列获取的消息数量。写多了，如果长时间得不到消费，数据就一直得不到处理
        auto-startup: true     #消费者自动启动
        default-requeue-rejected: true
    template:
      retry:
        enabled: true     #启用发送重试 队列满了发不进去时启动重试
        initial-interval: 1000     #1秒钟后重试一次
        max-attempts: 3     #最大重试次数 3次
        max-interval: 10000    #最大间隔 10秒钟
        multiplier: 1.0     #等待间隔 的倍数。如果为2  第一次 乘以2 等1秒， 第二次 乘以2 等2秒 ，第三次 乘以2 等4秒
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
logging: #showSql
  level:
    com:
      beiyou:
        dao : debug
jwt:
  secret: 123456
  expiration: 1000000
  header: token
---
spring:
  profiles: test



